# Generated by Django 5.2.16 on 2026-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
