# Generated by Django 5.2.16 on 2026-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productvariant_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
