# Generated by Django 5.2.16 on 2026-07-18 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_stocks', to='catalog.size')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='catalog.productvariant')),
            ],
            options={
                'verbose_name_plural': 'variant size stocks',
            },
        ),
    ]
