# Generated by Django 5.2.16 on 2026-07-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_variantsizestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.AddField(
            model_name='variantsizestock',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
