# Generated by Django 5.2.16 on 2026-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_productvariant_sku_variantsizestock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsizestock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
