# Generated by Django 5.2.16 on 2026-07-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_variantsizestock_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_mode', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('variant_size_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.variantsizestock')),
            ],
            options={
                'verbose_name_plural': 'Temporary orders',
            },
        ),
    ]
