# Generated by Django 5.2.16 on 2026-07-25 14:12

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='products/thumbnails/'),
        ),
    ]
