# Generated by Django 5.2.16 on 2026-07-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='thumbnail_image',
        ),
    ]
