# Generated by Django 5.2.16 on 2026-07-26 17:03

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_reel_url',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_thumbnail_url',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='products/instagram_thumbnails/'),
        ),
    ]
