# Generated by Django 5.2.16 on 2026-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_instagram_reel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verification_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
