# Generated by Django 5.2.16 on 2026-08-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_review_verification_status_alter_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
