# Generated by Django 5.2.16 on 2026-07-24 17:13

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('cover_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='stories/covers/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'story groups',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='stories/')),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=3000)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.CharField(blank=True, max_length=500)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='content.storygroup')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
